_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.11.5
            "5": 0.19.9
            "6": 4.36.2
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
dropout:
    value: 0.1
learning_rate:
    value: 1e-05
